Updates to Sources and help texts
rism-digital/muscat-guidelines pull request #29
Opened 2023-08-18 09:21 UTC by jenniferward

2023-08-18 09:57 UTC, ahankinson commented on default/en/cat_printed.md
> +If your institutions owns multiple copies (exemplars) of the same printed edition, create separate holdings records for each copy.
```suggestion
If your institution owns multiple copies (exemplars) of the same printed edition, create separate holdings records for each copy.  
```

2023-08-21 07:51 UTC, ahankinson commented on default/en/help_best_practices.md
> +If your copy is incomlete, revisions might still be possible, but make it clear in the **Source of description note (588)** that your copy is incomplete.
```suggestion
If your copy is incomplete, revisions might still be possible, but make it clear in the **Source of description note (588)** that your copy is incomplete.
```

2023-08-21 07:54 UTC, ahankinson commented on default/en/help_faqs.md
>  Muscat records are sent for publication in the [RISM Catalog](https://opac.rism.info/) once a month, at around the 19th of each month. Records are then visible a few days later.
```suggestion
Muscat records are sent for publication in the [RISM Catalog](https://opac.rism.info/) once a month, at around the 19th of each month. Records are then visible a few days later.  [RISM Online](https://rism.online) is updated daily, so new records and changes will appear there on the following day.
```

2023-08-21 07:55 UTC, ahankinson commented on default/en/institution_856.md
> +Enter the URL of the finding aid. Only enter one URL per field. All URLs must begin with http.
```suggestion
Enter the URL of the finding aid. Only enter one URL per field. All URLs must begin with `http` or `https`.
```

2023-08-21 08:10 UTC, ahankinson requested changes

2023-08-21 08:10 UTC, ahankinson commented on default/en/source_260.md
> +Furthermore, previous cataloging programs had two fields for dating. One was for numbers only and the second was a text field where numbers plus abbreviations such as _+, ca., ante, post,_ and _18.sc
```suggestion
Furthermore, previous cataloging programs had two fields for dating. One was for numbers only and the second was a text field where numbers plus abbreviations such as _+, ca., ante, post,_ and _18.sc_ or text such as _Easter 1805_ or _?1745?_ could be entered. Some legacy records, therefore, display two date indications, such as _1806 (1806 ca.)_. Dates written in the format XX.XX.XXXX are interpreted as DD.MM.YYYY.
```

2023-09-12 16:56 UTC, jenniferward reviewed
Thank you! I deleted the questionable sentence and approved the other changes.

2023-09-12 16:57 UTC, jenniferward commented on default/en/source_031.md
> +If there are multiple key signatures (such as if a movement changes frequently from major to minor and back again), enter the key signature of the incipit in question add an explanation in the field
I think I changed it (i.e., I deleted it).

2023-12-06 10:00 UTC, ahankinson approved these changes

2023-12-06 10:00 UTC, merged